# This is a basic workflow to help you get started with Actions

name: CI_PULLREQUEST

# Controls when the action will run. Triggers the workflow on pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build_release"
  build_pullrequest:
    # The type of runner that the job will run on
    runs-on: windows-2022
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      # Support longpaths
      - name: Support long paths
        run: git config --system core.longpaths true
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it                                                                                  
      - uses: actions/checkout@v4
        with:
          fetch-depth: '1'
          submodules: 'true'

      - name: Compile 
        run: dotnet build --no-incremental --configuration Release /p:Platform="Any CPU" src\net\NuReflector.sln
        
      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'
          
      - run: nuget pack src\net\NuReflectorCLI\NuReflectorCLI.nuspec -OutputDirectory .\bin

      - name: Reflect and Build net6.0 Maven POM files
        run: dotnet bin\net6.0\MASES.NuReflectorCLI.dll -PackagesFile .github\workflows\packages.json

      - name: Reflect and Build net462 Maven POM files
        run: .\bin\net462\MASES.NuReflectorCLI -PackagesFile .github\workflows\packages_net462.json

      - name: Clear documentation folder 
        run: Remove-Item .\docs\* -Recurse -Force -Exclude _config.yml,CNAME

      - run: dotnet tool update -g docfx

      - name: Build documentation
        run: |
          cd src\documentation
          docfx
