# This is a basic workflow to help you get started with Actions

name: CI_WEEKLYBUILD

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  schedule:
  # * is a special character in YAML so you have to quote this string
  - cron:  '0 2 * * 6'

# This workflow contains two jobs called "build_windows"
jobs:
  # Now run "build_windows"
  build_windows:
    # The type of runner that the job will run on
    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:   
      # Runs a set of commands using the runners shell
      # Support longpaths
      - name: Support long paths
        run: git config --system core.longpaths true
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: '1'
          submodules: 'true'

      - name: Compile 
        run: dotnet build --no-incremental --configuration Release /p:Platform="Any CPU" src\NuReflector.sln

      - name: Reflect and Build net6.0 Maven POM files
        run: dotnet bin\net6.0\MASES.NuReflectorCLI.dll -PackagesFile .github\workflows\packages.json
 
      - name: Reflect and Build net462 Maven POM files
        run: .\bin\net462\MASES.NuReflectorCLI -PackagesFile .github\workflows\packages_net462.json

      - name: Commit source changes
        uses: EndBug/add-and-commit@v5
        if: ${{ github.repository_owner == 'masesgroup'}} #do not push any changes outside main repo
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          add: '.\netreflected\*.*'
          message: Update sources after nightly build check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
